spring:
  profiles:
    active: development
  security:
    oauth2:
      client:
        clientId: 726523ff10744c7492baf193993d378a
        clientSecret: 889171cdbc764773828c5e970656ec51
    user:
      name: user
      password: pass
